import 'package:drill_deck/app_bloc/app_bloc.dart';
import 'package:drill_deck/features/backup/backup_payload.dart';
import 'package:drill_deck/repositories/storage_repository.dart';
import 'package:drill_deck/theme/app_colors.dart';
import 'package:drill_deck/theme/mono_typography.dart';
import 'package:flutter/material.dart' hide Card;
import 'package:flutter_bloc/flutter_bloc.dart';

class ImportSheet extends StatefulWidget {
  const ImportSheet({super.key});

  static Future<void> show(BuildContext context) {
    return showModalBottomSheet<void>(
      context: context,
      backgroundColor: AppColors.surface,
      isScrollControlled: true,
      builder: (_) => Padding(
        padding: EdgeInsets.only(
          bottom: MediaQuery.of(context).viewInsets.bottom,
        ),
        child: const ImportSheet(),
      ),
    );
  }

  @override
  State<ImportSheet> createState() => _ImportSheetState();
}

class _ImportSheetState extends State<ImportSheet> {
  final _controller = TextEditingController();
  String? _error;
  String? _success;

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  Future<void> _doImport() async {
    final text = _controller.text.trim();
    if (text.isEmpty) {
      setState(() => _error = 'Paste JSON first.');
      return;
    }
    final appState = context.read<AppBloc>().state;
    final current = appState.snapshot;
    if (current == null) {
      setState(() => _error = 'App state not loaded yet.');
      return;
    }
    try {
      final result = BackupImport.merge(text, current);
      final storage = context.read<StorageRepository>();
      await storage.save(result.snapshot);
      if (!mounted) return;
      setState(() {
        _error = null;
        _success = 'Imported.';
      });
      await Future<void>.delayed(const Duration(milliseconds: 600));
      if (mounted) Navigator.of(context).pop();
    } on FormatException catch (e) {
      setState(() => _error = e.message);
    } catch (e) {
      setState(() => _error = 'Import failed: $e');
    }
  }

  @override
  Widget build(BuildContext context) {
    final mono = Theme.of(context).extension<MonoTypography>()!;
    return SafeArea(
      top: false,
      child: Padding(
        padding: const EdgeInsets.fromLTRB(20, 20, 20, 28),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text('Import', style: Theme.of(context).textTheme.titleLarge),
            const SizedBox(height: 4),
            Text(
              'Paste JSON exported from another device or generated by Claude.',
              style: mono.hint,
            ),
            const SizedBox(height: 14),
            TextField(
              controller: _controller,
              maxLines: 10,
              minLines: 6,
              style: const TextStyle(
                fontSize: 12,
                fontFamilyFallback: ['SF Mono', 'Menlo', 'Consolas'],
                color: AppColors.text,
              ),
              decoration: const InputDecoration(
                filled: true,
                fillColor: AppColors.ink,
                hintText:
                    '{"version":1,"kind":"deck", ...}',
                border: OutlineInputBorder(
                  borderRadius: BorderRadius.all(Radius.circular(11)),
                ),
              ),
            ),
            if (_error != null) ...[
              const SizedBox(height: 10),
              Text(_error!, style: mono.hint.copyWith(color: AppColors.danger)),
            ],
            if (_success != null) ...[
              const SizedBox(height: 10),
              Text(_success!, style: mono.hint.copyWith(color: AppColors.got)),
            ],
            const SizedBox(height: 18),
            Row(
              children: [
                Expanded(
                  child: OutlinedButton(
                    onPressed: () => Navigator.of(context).pop(),
                    child: const Text('Cancel'),
                  ),
                ),
                const SizedBox(width: 10),
                Expanded(
                  child: FilledButton(
                    onPressed: _doImport,
                    child: const Text('Import'),
                  ),
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }
}
